/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
// Register addresses from RM0440
#define RCC_BASE        0x40021000
#define RCC_AHB2ENR     (*(volatile unsigned int *)(RCC_BASE + 0x4C))

#define GPIOA_BASE      0x48000000
#define GPIOA_MODER     (*(volatile unsigned int *)(GPIOA_BASE + 0x00))
#define GPIOA_ODR       (*(volatile unsigned int *)(GPIOA_BASE + 0x14))

int main(void)
{
    // Enable GPIOA clock
    RCC_AHB2ENR |= (1 << 0);

    // Set PA5 as output
    GPIOA_MODER &= ~(0x3 << 10);
    GPIOA_MODER |=  (0x1 << 10);

    // Blink forever
    for(;;)
    {
        GPIOA_ODR ^= (1 << 5);
        for(volatile int i = 0; i < 100000; i++);
    }
}
