/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
// Register addresses from RM0440
#define RCC_BASE        0x40021000
#define RCC_AHB2ENR     (*(volatile unsigned int *)(RCC_BASE + 0x4C))

#define GPIOA_BASE      0x48000000
#define GPIOA_MODER     (*(volatile unsigned int *)(GPIOA_BASE + 0x00))
#define GPIOA_ODR       (*(volatile unsigned int *)(GPIOA_BASE + 0x14))

#define GPIOC_BASE		0x48000800
#define GPIOC_MODER     (*(volatile unsigned int *)(GPIOC_BASE + 0x00))
#define GPIOC_IDR       (*(volatile unsigned int *)(GPIOC_BASE + 0x10))

int main(void)
{
    // Enable GPIO clock
//	RCC->AHB2ENR |= (1<<2);
//	RCC->AHB2ENR |= 1;
		//Cleaner version
	RCC_AHB2ENR |= (1<<2) | (1<<0);
	// Register and Set PC13 Pin
	GPIOC_MODER &= ~(0b11<<26);
	GPIOA_MODER &= ~(0b11<<10);
	GPIOA_MODER |= (0b01<<10);

    // Blink forever
    for(;;)
    {
    	// Input Data reading
		if (GPIOC_IDR & (1<<13)){
			// LED turns on
			GPIOA_ODR |= (1<<5);
		}
		else{
			// LED turns off
			GPIOA_ODR &= ~(1<<5);
		}
    }
}
